/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sarisaristore;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ShowMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowMenu.class.getName());

    /**
     * Creates new form ShowMenu
     */
    public ShowMenu() {
        initComponents();
    }
    
//    public String category;
    ArrayList<Product> drinks = new ArrayList<>();
    ArrayList<Product> snacks = new ArrayList<>();
    ArrayList<Cart> myCart = new ArrayList<>();
    ArrayList<Product> currentData = null;
    
    public ShowMenu(String category) {
        initComponents();
        
        drinks.add(new Product("Coke", 25, 50));
        drinks.add(new Product("Coffee", 50, 10));
        drinks.add(new Product("Sting", 35, 20));
        
        snacks.add(new Product("Mang Juan", 15, 20));
        snacks.add(new Product("Loaded", 20, 10));
        snacks.add(new Product("Skyflakes", 10, 15));
        
        loadCategory(category);
        lblCategory.setText("CATEGORY: " + category.toUpperCase());
    }
    
    public void loadCategory(String cat) {
        if (cat.equalsIgnoreCase("drinks")) 
            displayAll(drinks);
        else if (cat.equalsIgnoreCase("snacks")) 
            displayAll(snacks);
        else 
            txtareaPrint.setText("Invalid");
    }
    
    private void displayAll(ArrayList<Product> data) {
        int index = 1;
        
        String display = "ID\tProduct\tPrice\tStock\n";
        display += "-------------------------------------------------------------------------------\n";
        for(Product p : data) {
            display += index + "\t"  + p.getName() + "\t₱" + p.getPrice() + "\t" + p.getStock() + "pcs left\n";
            index++;
        }
        
        txtareaPrint.setText(display);
        currentData = data;
    }
    
    public void addToCart(ArrayList<Product> data) {
        int choice = (int) jSpinnerChoice.getValue() - 1 ;
        int quantity = (int) jSpinnerQuantity.getValue();
        Product userChoice = data.get(choice);
        boolean isFound = false;
        
        if (choice <= -1 || choice > data.size() - 1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Invalid input. Please enter a valid choice.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (quantity > userChoice.getStock()) {
            JOptionPane.showMessageDialog(rootPane, 
                    "No enough stock. There are " + userChoice.getStock() + "pcs left.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        for (Cart cart : myCart) {
            if (cart.getName().equalsIgnoreCase(userChoice.getName())) {                
                cart.setQuantity(cart.getQuantity() + quantity);
                isFound = true;
                break;
            }
        }
        
        if (!isFound) {
            myCart.add(new Cart(userChoice.getName(), userChoice.getPrice(), quantity));
        }
        
        userChoice.updateStock(userChoice.getStock() - quantity);
        displayAll(data); 
        JOptionPane.showMessageDialog(rootPane, 
                "Added Successfuly", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public void showCart() {
        String viewCart = "Current Items: \n\n";
        
        if (myCart.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, 
                    "No item here", 
                    "View Cart", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        for (Cart cart : myCart) {
            viewCart += cart.getName() + " "
                    + "₱" + cart.getPrice() + " "
                    + cart.getQuantity() +"pc(s)\n"
            ;
        }
        
        JOptionPane.showMessageDialog(rootPane, 
                viewCart, 
                "View Cart", 
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategory = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaPrint = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        jSpinnerChoice = new javax.swing.JSpinner();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnViewCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        lblCategory.setText("Category:");

        btnBack.setText("back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtareaPrint.setEditable(false);
        txtareaPrint.setColumns(20);
        txtareaPrint.setRows(5);
        jScrollPane1.setViewportView(txtareaPrint);

        jLabel1.setText("Enter ID choice: ");

        btnAddToCart.setText("add to cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        jSpinnerQuantity.setValue(1);

        jLabel2.setText("Enter quantity:");

        btnViewCart.setText("view cart");
        btnViewCart.addActionListener(this::btnViewCartActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewCart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddToCart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerChoice)
                                    .addComponent(jSpinnerQuantity))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart)
                    .addComponent(btnViewCart))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainStore mainStore = new MainStore();
        mainStore.setLocationRelativeTo(null);
        mainStore.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        addToCart(currentData);
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
        // TODO add your handling code here:
        showCart();
    }//GEN-LAST:event_btnViewCartActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ShowMenu().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerChoice;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JTextArea txtareaPrint;
    // End of variables declaration//GEN-END:variables
}
